### ISSUE TITLE
Nowhere to put bot token?

### ISSUE THREAD

**Issue by kerryphisher** [BramEsendam/DiscordBotTemplate#8]
"Basic bot: Add your bot token to the ConfigData.json file."
Where is this file? It is referenced in ConfigData.cs, but it doesn't exist anywhere.

**Comment by BrammyS** [comment]
It should generate that file the first time you run it.
It should be located at `/Bot/bin/Debug/net5.0/Configs` if you run it in debug mode.

**Comment by kerryphisher** [comment]
Appreciated.
